fail_fast: true

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
        stages: [commit]
    -   id: end-of-file-fixer
        stages: [commit]
    -   id: trailing-whitespace
        stages: [commit]
    -   id: detect-private-key
        stages: [commit]
    -   id: check-case-conflict
        stages: [commit]
    -   id: check-executables-have-shebangs
        stages: [commit]
    -   id: check-merge-conflict
        stages: [commit]
    -   id: debug-statements
        stages: [commit]
    -   id: name-tests-test
        stages: [commit]

-   repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
        args: ["--profile", "black"]
        stages: [commit]
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    - id: black
      stages: [commit]
-   repo: https://github.com/pycqa/flake8
    rev: '5.0.4'
    hooks:
    - id: flake8
      additional_dependencies:
        - "flake8-coding==1.3.2"
        - "flake8-copyright==0.2.3"
        - "flake8-debugger==4.1.2"
      stages: [commit]
#-   repo: https://github.com/PyCQA/bandit
#    rev: '1.7.5'
#    hooks:
#    - id: bandit

default_language_version:
  python: python3
